### PR TITLE
Add `eslint-plugin-react-hooks`

### PR DESCRIPTION
**Pull request by jgierer12**
Depends on https://github.com/KidkArolis/eslint-plugin-healthier/pull/1
Fixes https://github.com/KidkArolis/eslint-config-healthier/issues/2

### CODE REVIEW

**Comment by jgierer12** [comment]
`plugin`, not `config` :sweat_smile:

**Comment by KidkArolis** [comment]
Release the plugin as eslint-plugin-healthier@1.1.0.

**Comment by jgierer12** [comment]
Upgraded `eslint-plugin-healthier` and changed readme accordingly. :shipit:

**Comment by KidkArolis** [comment]
Tested, works great!

image

Found a potential bug in eslint-plugin-react-hooks: https://twitter.com/kidkarolis/status/1098333622724104199.

Will release shortly.

**Pull request merged**
